// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSH58eaJjqkFvGDMYu0sT7Oc4zxPJzpTc',
    appId: '1:1062680284266:web:5b3b50b1aad2691d768e13',
    messagingSenderId: '1062680284266',
    projectId: 'mehendi-studio',
    authDomain: 'mehendi-studio.firebaseapp.com',
    storageBucket: 'mehendi-studio.appspot.com',
    measurementId: 'G-QW1VN7XY0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuOwYOd9TPcxeh3Wv-EwZ2Nv0Nv7mAP40',
    appId: '1:1062680284266:android:7a12daf15208eee6768e13',
    messagingSenderId: '1062680284266',
    projectId: 'mehendi-studio',
    storageBucket: 'mehendi-studio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoFLF1hYc9kwOQtlxwl-pLlzMgWAe2xkU',
    appId: '1:1062680284266:ios:af703ce8ab390c5f768e13',
    messagingSenderId: '1062680284266',
    projectId: 'mehendi-studio',
    storageBucket: 'mehendi-studio.appspot.com',
    iosClientId: '1062680284266-f3l9f1gu0kd0ne1mhfsgv87apjgh9sq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehendiDesignApp',
  );
}
